### ISSUE TITLE
Remake the frontend to typescript

### ISSUE THREAD

**Issue by Descatres** [EdgarTip/ShiftAppens#1]
## TODO: 

- [ ] Backup the files from the previous version
- [ ] Create a typescript project
- [ ] Remake the code to make it work again, in order to further develop it
